#!/bin/sh -l
#SBATCH -A partner
#SBATCH --nodes=1
#SBATCH --gpus=1
#SBATCH --time=24:00:00
#SBATCH --job-name TrainNN

cd $SLURM_SUBMIT_DIR

#python3 main_train_dncnn.py -opt 'options/train_dncnn_dna_sigma5_maxepoch1000.json'

#python3 main_train_dncnn.py -opt 'options/train_dncnn_dna_sigma13_maxepoch1000.json'

#python3 main_train_dncnn.py -opt 'options/train_dncnn_dna_sigma25_maxepoch1000.json'

python3 main_train_dncnn.py -opt 'options/train_dncnn_dna_sigma25_24hours.json'

